### ISSUE TITLE
Split the config file into multiple ones

### ISSUE THREAD

**Issue by jose-caballero** [stfc/pam_oauth2_device#3]
Split /etc/pam_oauth2_device/config.json into multiple files. 

Most important reason is not to have in the same file all the information about users -as well as other variables- and the ID & SECRET to contact the remote OAuth service. This way, the rest of the information can be updated as needed by the configuration management system (CMS) of your choice, w/o having to include the secrets in that CMS.

**Comment by jjensenral** [comment]
Closed by v1.01 (in the master branch)
